# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/elephone/p6000/setup-makefiles.sh

PRODUCT_COPY_FILES += \
 vendor/elephone/p6000/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
 vendor/elephone/p6000/proprietary/bin/akmd8963:system/bin/akmd8963 \
 vendor/elephone/p6000/proprietary/bin/akmd8975:system/bin/akmd8975 \
 vendor/elephone/p6000/proprietary/bin/akmd09911:system/bin/akmd09911 \
 vendor/elephone/p6000/proprietary/bin/ami304d:system/bin/ami304d \
 vendor/elephone/p6000/proprietary/bin/bmm050d:system/bin/bmm050d \
 vendor/elephone/p6000/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
 vendor/elephone/p6000/proprietary/bin/qmc5983d:system/bin/qmc5983d \
 vendor/elephone/p6000/proprietary/bin/xlog:system/bin/xlog \
 vendor/elephone/p6000/proprietary/bin/thermal_manager:system/bin/thermal_manager \
 vendor/elephone/p6000/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
 vendor/elephone/p6000/proprietary/bin/MtkCodecService:system/bin/MtkCodecService \
 vendor/elephone/p6000/proprietary/bin/muxreport:system/bin/muxreport \
 vendor/elephone/p6000/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
 vendor/elephone/p6000/proprietary/bin/lsm303md:system/bin/lsm303md \
 vendor/elephone/p6000/proprietary/bin/6620_launcher:system/bin/6620_launcher \
 vendor/elephone/p6000/proprietary/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
 vendor/elephone/p6000/proprietary/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
 vendor/elephone/p6000/proprietary/bin/gsm0710muxd:system/bin/gsm0710muxd \
 vendor/elephone/p6000/proprietary/bin/drvbd:system/bin/drvbd \
 vendor/elephone/p6000/proprietary/bin/wmt_loader:system/bin/wmt_loader \
 vendor/elephone/p6000/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
 vendor/elephone/p6000/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
 vendor/elephone/p6000/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
 vendor/elephone/p6000/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
 vendor/elephone/p6000/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
 vendor/elephone/p6000/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
 vendor/elephone/p6000/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
 vendor/elephone/p6000/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
 vendor/elephone/p6000/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
 vendor/elephone/p6000/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
 vendor/elephone/p6000/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
 vendor/elephone/p6000/proprietary/lib/libnvram.so:system/lib/libnvram.so \
 vendor/elephone/p6000/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
 vendor/elephone/p6000/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
 vendor/elephone/p6000/proprietary/lib/lib3a.so:system/lib/lib3a.so \
 vendor/elephone/p6000/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
 vendor/elephone/p6000/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
 vendor/elephone/p6000/proprietary/lib/hw/gralloc.mt6752.so:system/lib/hw/gralloc.mt6752.so \
 vendor/elephone/p6000/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
 vendor/elephone/p6000/proprietary/lib/hw/hwcomposer.mt6752.so:system/lib/hw/hwcomposer.mt6752.so \
 vendor/elephone/p6000/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
 vendor/elephone/p6000/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
 vendor/elephone/p6000/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
 vendor/elephone/p6000/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
 vendor/elephone/p6000/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
 vendor/elephone/p6000/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
 vendor/elephone/p6000/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
 vendor/elephone/p6000/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
 vendor/elephone/p6000/proprietary/lib/libmnl.so:system/lib/libmnl.so \
 vendor/elephone/p6000/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
 vendor/elephone/p6000/proprietary/lib/libion.so:system/lib/libion.so \
 vendor/elephone/p6000/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
 vendor/elephone/p6000/proprietary/lib/libbwc.so:system/lib/libbwc.so \
 vendor/elephone/p6000/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
 vendor/elephone/p6000/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
 vendor/elephone/p6000/proprietary/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
 vendor/elephone/p6000/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
 vendor/elephone/p6000/proprietary/lib/libimageio.so:system/lib/libimageio.so \
 vendor/elephone/p6000/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
 vendor/elephone/p6000/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
 vendor/elephone/p6000/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
 vendor/elephone/p6000/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
 vendor/elephone/p6000/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
 vendor/elephone/p6000/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
 vendor/elephone/p6000/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
 vendor/elephone/p6000/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
 vendor/elephone/p6000/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
 vendor/elephone/p6000/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
 vendor/elephone/p6000/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
 vendor/elephone/p6000/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
 vendor/elephone/p6000/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
 vendor/elephone/p6000/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
 vendor/elephone/p6000/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
 vendor/elephone/p6000/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
 vendor/elephone/p6000/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
 vendor/elephone/p6000/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
 vendor/elephone/p6000/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
 vendor/elephone/p6000/proprietary/lib/libssladp.so:system/lib/libssladp.so \
 vendor/elephone/p6000/proprietary/lib/libm4u.so:system/lib/libm4u.so \
 vendor/elephone/p6000/proprietary/lib/libutilrilmtk.so:system/lib/libutilrilmtk.so \
 vendor/elephone/p6000/proprietary/xbin/mnld:system/xbin/mnld \
 vendor/elephone/p6000/proprietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6571_lm_patch_e1_0_hdr.bin:system/etc/firmware/mt6571_lm_patch_e1_0_hdr.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/mt6571_lm_patch_e1_1_hdr.bin:system/etc/firmware/mt6571_lm_patch_e1_1_hdr.bin \
 vendor/elephone/p6000/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
 vendor/elephone/p6000/proprietary/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
 vendor/elephone/p6000/proprietary/etc/firmware/WIFI_RAM_CODE_6752:system/etc/firmware/WIFI_RAM_CODE_6752 \
 vendor/elephone/p6000/proprietary/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6 \
 vendor/elephone/p6000/proprietary/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
 vendor/elephone/p6000/proprietary/etc/firmware/WIFI_RAM_CODE_MT6630:system/etc/firmware/WIFI_RAM_CODE_MT6630
